# Generated by Django 6.0 on 2026-04-13 23:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('blood_type', models.CharField(blank=True, max_length=5, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('verification_status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ems_schema"."users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmergencyReport',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reporter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('permission_camera', models.BooleanField(default=False)),
                ('permission_location', models.BooleanField(default=False)),
                ('permission_mic', models.BooleanField(default=False)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='emergency_media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'emergency_reports',
                'managed': True,
            },
        ),
    ]
