# Generated by Django 6.0 on 2026-04-15 23:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('El7a2ny_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_type', models.CharField(default='normal', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('blood_type', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('national_id', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('emergency_contacts', models.JSONField(blank=True, default=list, null=True)),
                ('connected_devices', models.JSONField(blank=True, default=list, null=True)),
                ('share_location', models.BooleanField(default=False)),
                ('camera', models.BooleanField(default=False)),
                ('mic', models.BooleanField(default=False)),
                ('status', models.CharField(default='active', max_length=50)),
                ('verification_status', models.CharField(default='pending', max_length=50)),
                ('admin_id', models.UUIDField(blank=True, null=True)),
                ('field', models.CharField(blank=True, max_length=255, null=True)),
                ('external_certificates', models.JSONField(blank=True, default=list, null=True)),
                ('id_card_front', models.CharField(blank=True, max_length=500, null=True)),
                ('id_card_back', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'ems_schema"."users',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
