# Generated by Django 6.0 on 2026-04-19 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('El7a2ny_backend', '0002_user_delete_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
