# Generated by Django 6.0 on 2026-04-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('El7a2ny_backend', '0005_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('author_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author_role', models.CharField(default='citizen', max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_info', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('participants_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ems_schema"."initiatives',
                'managed': True,
            },
        ),
    ]
