# Generated by Django 6.0.4 on 2026-04-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('El7a2ny_backend', '0005_alter_user_options'),
    ]

    operations = [

        migrations.AddField(
            model_name='user',
            name='has_vehicle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sensor_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='smart_watch_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='volunteer_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
