# Generated by Django 6.0.4 on 2026-04-29 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('El7a2ny_backend', '0006_add_media_files'),
        ('El7a2ny_backend', '0006_helpinitiative_remove_user_id_card_back_and_more'),
    ]

    operations = [
    ]
