# Generated by Django 6.0.4 on 2026-04-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('El7a2ny_backend', '0007_merge_20260430_0040'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RemoveField(
                    model_name='incident',
                    name='media',
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='incident',
                    name='media',
                ),
                migrations.RemoveField(
                    model_name='user',
                    name='id_card_back',
                ),
                migrations.RemoveField(
                    model_name='user',
                    name='id_card_front',
                ),
                migrations.AddField(
                    model_name='user',
                    name='has_vehicle',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='user',
                    name='sensor_model',
                    field=models.CharField(blank=True, max_length=255, null=True),
                ),
                migrations.AddField(
                    model_name='user',
                    name='skills',
                    field=models.TextField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='user',
                    name='smart_watch_model',
                    field=models.CharField(blank=True, max_length=255, null=True),
                ),
                migrations.AddField(
                    model_name='user',
                    name='volunteer_enabled',
                    field=models.BooleanField(default=False),
                ),
            ]
        )
    ]
