# Generated by Django 6.0.4 on 2026-05-01 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('El7a2ny_backend', '0007_password_reset_token'),
        ('El7a2ny_backend', '0008_remove_incident_media_remove_user_id_card_back_and_more'),
    ]

    operations = [
    ]
