# Generated by Django 6.0.4 on 2026-05-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('El7a2ny_backend', '0009_merge_20260501_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('author_name', models.CharField(max_length=255)),
                ('author_role', models.CharField(default='citizen', max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_info', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('participants_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ems_schema"."initiatives',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='helpinitiative',
            options={},
        ),
        migrations.RemoveField(
            model_name='helpinitiative',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='helpinitiative',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='helpinitiative',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='helpinitiative',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='helpinitiative',
            name='location',
        ),
        migrations.RemoveField(
            model_name='helpinitiative',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='helpinitiative',
            name='participants_count',
        ),
        migrations.AlterModelTable(
            name='helpinitiative',
            table=None,
        ),
    ]
