# Generated by Django 6.0 on 2026-05-03 14:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('El7a2ny_backend', '0010_initiative_alter_helpinitiative_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
