# Generated by Django 6.0 on 2026-05-03 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('El7a2ny_backend', '0011_initiative_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='El7a2ny_backend.user'),
        ),
    ]
