# Generated by Django 5.0.6 on 2026-05-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('El7a2ny_backend', '0012_initiative_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_plus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='renewal_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
