# Generated by Django 6.0 on 2026-05-08 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('El7a2ny_backend', '0014_sensorreading'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_rating', models.FloatField(default=0.0)),
                ('police_rating', models.FloatField(default=0.0)),
                ('ambulance_rating', models.FloatField(default=0.0)),
                ('fire_dept_rating', models.FloatField(default=0.0)),
                ('el7a2ny_plus_rating', models.FloatField(default=0.0)),
                ('volunteers_helpful', models.BooleanField(blank=True, null=True)),
                ('report_fake', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ratings', to='El7a2ny_backend.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_real_report', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_ratings', to='El7a2ny_backend.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
