# Generated by Django 6.0.4 on 2026-05-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('El7a2ny_backend', '0015_userrating_volunteerrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='ai_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
