# Generated by Django 6.0 on 2026-05-12 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('El7a2ny_backend', '0015_userrating_volunteerrating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpinitiative',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='sensorreading',
            options={'managed': True, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='userrating',
            options={'managed': True, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='volunteerrating',
            options={'managed': True, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='helpinitiative',
            table='ems_schema"."help_initiatives',
        ),
        migrations.AlterModelTable(
            name='sensorreading',
            table='ems_schema"."sensor_readings',
        ),
        migrations.AlterModelTable(
            name='userrating',
            table='ems_schema"."user_ratings',
        ),
        migrations.AlterModelTable(
            name='volunteerrating',
            table='ems_schema"."volunteer_ratings',
        ),
    ]
