# Generated by Django 6.0.4 on 2026-05-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('El7a2ny_backend', '0016_incident_ai_instructions_incident_ai_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='ai_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='image_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
