# Generated by Django 6.0 on 2026-05-14 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('El7a2ny_backend', '0016_alter_helpinitiative_options_and_more'),
        ('El7a2ny_backend', '0017_add_ai_analysis_and_image_hash'),
    ]

    operations = [
    ]
