# Generated by Django 6.0 on 2026-05-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('El7a2ny_backend', '0018_merge_20260514_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
