# Generated by Django 6.0.4 on 2026-05-14 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('El7a2ny_backend', '0020_sponsorrequest'),
    ]

    operations = [
    ]
