# Generated by Django 6.0.4 on 2026-05-14 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('El7a2ny_backend', '0021_delete_sponsorrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SponsorRequest',
        ),
    ]
