# Generated by Django 6.0.4 on 2026-05-15 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('El7a2ny_backend', '0018_merge_20260514_0054'),
        ('El7a2ny_backend', '0022_delete_sponsorrequest'),
    ]

    operations = [
    ]
