# Generated by Django 6.0.4 on 2026-05-15 18:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('El7a2ny_backend', '0023_merge_20260515_2157'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Responder',
        #     fields=[
        #         ('responder_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
        #         ('incident_id', models.UUIDField()),
        #         ('user_id', models.UUIDField()),
        #         ('response_time', models.DurationField(blank=True, null=True)),
        #         ('lat', models.FloatField(blank=True, null=True)),
        #         ('lng', models.FloatField(blank=True, null=True)),
        #         ('last_location_updated', models.DateTimeField(blank=True, null=True)),
        #     ],
        #     options={
        #         'db_table': 'responders',
        #         'managed': True,
        #     },
        # ),
        migrations.RemoveField(
            model_name='incident',
            name='ai_analysis',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='ai_instructions',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='ai_summary',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='image_hash',
        ),
        migrations.AddField(
            model_name='incident',
            name='current_volunteers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incident',
            name='total_volunteers',
            field=models.IntegerField(default=0),
        ),
    ]
