# Generated by Django 6.0.4 on 2026-05-18 21:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('El7a2ny_backend', '0024_responder_remove_incident_ai_analysis_and_more'),
    ]

    operations = [

        migrations.CreateModel(
            name='IncidentAIAnalysis',
            fields=[
                ('analysis_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_type', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Unknown', 'Unknown')], default='Unknown', max_length=20)),
                ('triage_level', models.CharField(choices=[('Red', 'Red'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Black', 'Black')], default='Yellow', max_length=10)),
                ('urgency_score', models.IntegerField(default=5)),
                ('risk_level', models.CharField(blank=True, max_length=255, null=True)),
                ('dispatch_priority', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('responder_briefing', models.TextField(blank=True, null=True)),
                ('instructions', models.JSONField(default=list)),
                ('responders_needed', models.JSONField(default=list)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('voice', 'Voice'), ('text', 'Text')], max_length=10, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.OneToOneField(db_column='incident_id', on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='El7a2ny_backend.incident')),
            ],
            options={
                'db_table': 'ems_schema"."incident_ai_analyses',
                'ordering': ['-analyzed_at'],
                'managed': True,
            },
        ),
    ]
