# Generated by Django 5.0.6 on 2026-05-18 08:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('El7a2ny_backend', '0024_responder_remove_incident_ai_analysis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('responder_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_id', models.UUIDField()),
                ('user_id', models.UUIDField()),
                ('response_time', models.DurationField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('last_location_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'responders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IncidentChat',
            fields=[
                ('chat_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'incident_chats',
                'managed': True,
                'indexes': [models.Index(fields=['incident_id', '-updated_at'], name='incident_ch_inciden_d4559a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_id', models.UUIDField()),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_type', models.CharField(choices=[('user', 'Report User'), ('volunteer', 'Volunteer'), ('admin', 'Admin'), ('system', 'System')], max_length=20)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('chat', models.ForeignKey(db_column='chat_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='El7a2ny_backend.incidentchat')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
                'managed': True,
                'indexes': [models.Index(fields=['chat', '-created_at'], name='chat_messag_chat_id_281c8a_idx')],
            },
        ),
    ]
