# Generated by Django 6.0.4 on 2026-05-22 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('El7a2ny_backend', '0025_responder_incidentaianalysis'),
        ('El7a2ny_backend', '0025_responder_incidentchat_chatmessage'),
    ]

    operations = [
    ]
