# Generated by Django 6.0.5 on 2026-05-22 21:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('El7a2ny_backend', '0027_alter_chatmessage_table_alter_incidentchat_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentaianalysis',
            name='community_votes_fake',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incidentaianalysis',
            name='community_votes_real',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incidentaianalysis',
            name='detected_objects',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='incidentaianalysis',
            name='fake_probability',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='incidentaianalysis',
            name='is_real',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='incidentaianalysis',
            name='raw_detections',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='incidentaianalysis',
            name='summary_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentaianalysis',
            name='summary_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentaianalysis',
            name='user_instructions_ar',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='incidentaianalysis',
            name='user_instructions_en',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='incidentaianalysis',
            name='verification_methods',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='incidentaianalysis',
            name='volunteer_instructions_ar',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='incidentaianalysis',
            name='volunteer_instructions_en',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='incidentaianalysis',
            name='volunteers_recommended',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='trust_score',
            field=models.FloatField(default=1.0),
        ),
        migrations.CreateModel(
            name='IncidentDispatch',
            fields=[
                ('dispatch_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_requested', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='El7a2ny_backend.incident')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_dispatches', to='El7a2ny_backend.user')),
            ],
            options={
                'db_table': 'ems_schema"."incident_dispatches',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lng', models.FloatField(blank=True, null=True)),
                ('has_first_aid', models.BooleanField(default=False)),
                ('has_firefighting', models.BooleanField(default=False)),
                ('has_rescue_training', models.BooleanField(default=False)),
                ('has_transportation', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to='El7a2ny_backend.user')),
            ],
            options={
                'db_table': 'ems_schema"."volunteer_profiles',
                'managed': True,
            },
        ),
    ]
