# Generated by Django 6.0.5 on 2026-05-24 22:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('El7a2ny_backend', '0028_incidentaianalysis_community_votes_fake_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ems_schema"."admin_logs',
                'ordering': ['-timestamp'],
                'managed': True,
            },
        ),
    ]
