# Generated by Django 6.0.5 on 2026-05-25 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('El7a2ny_backend', '0028_sensorreading_alert_level'),
        ('El7a2ny_backend', '0030_user_banned_until'),
    ]

    operations = [
    ]
