# Generated by Django 6.0.5 on 2026-05-27 00:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('El7a2ny_backend', '0031_merge_20260526_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('course_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ar', models.CharField(max_length=255)),
                ('description_en', models.TextField()),
                ('description_ar', models.TextField()),
                ('category_en', models.CharField(max_length=100)),
                ('category_ar', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('badge_name_en', models.CharField(default='Certified Responder', max_length=255)),
                ('badge_name_ar', models.CharField(default='مسعف معتمد', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ems_schema"."training_courses',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='incidentaianalysis',
            options={'managed': True},
        ),
        migrations.CreateModel(
            name='CourseQuizQuestion',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text_en', models.TextField()),
                ('question_text_ar', models.TextField()),
                ('options_en', models.JSONField(default=list)),
                ('options_ar', models.JSONField(default=list)),
                ('correct_option_index', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='El7a2ny_backend.trainingcourse')),
            ],
            options={
                'db_table': 'ems_schema"."course_quiz_questions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TrainingLesson',
            fields=[
                ('lesson_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_index', models.IntegerField(default=0)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ar', models.CharField(max_length=255)),
                ('content_en', models.TextField()),
                ('content_ar', models.TextField()),
                ('reading_time_minutes', models.IntegerField(default=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='El7a2ny_backend.trainingcourse')),
            ],
            options={
                'db_table': 'ems_schema"."training_lessons',
                'ordering': ['order_index'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VolunteerCourseProgress',
            fields=[
                ('progress_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='El7a2ny_backend.trainingcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to='El7a2ny_backend.user')),
            ],
            options={
                'db_table': 'ems_schema"."volunteer_course_progress',
                'managed': True,
                'unique_together': {('user', 'course')},
            },
        ),
    ]
