# Generated by Django 6.0.5 on 2026-05-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('El7a2ny_backend', '0032_trainingcourse_alter_incidentaianalysis_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='is_irl',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='location_info_ar',
            field=models.CharField(default='مركز تدريب القاهرة', max_length=255),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='location_info_en',
            field=models.CharField(default='Cairo Training Center', max_length=255),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='price',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='schedule_info_ar',
            field=models.CharField(default='الجمعة الساعة ٢:٠٠ ظهراً', max_length=255),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='schedule_info_en',
            field=models.CharField(default='Fridays at 2:00 PM', max_length=255),
        ),
    ]
