# Generated by Django 5.0.6 on 2026-05-28 10:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('El7a2ny_backend', '0033_trainingcourse_is_irl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('sponsor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('company_type', models.CharField(choices=[('cars', 'Cars & Roadside'), ('insurance', 'Insurance'), ('medical', 'Medical')], max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='active', max_length=20)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('sponsorship_level', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='silver', max_length=20)),
                ('admin_id', models.UUIDField(blank=True, null=True)),
                ('incident_id', models.UUIDField(blank=True, null=True)),
                ('training_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ems_schema"."sponsors',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
